---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A boat beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —  
Children three that nestle near,  
Eager eye and willing ear,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Mother doesn't want a dog.  
Mother says they smell,  
And never sit when you say sit,  
Or even when you yell.  
  
When you come home late at night  
And there is ice and snow,  
You have to go back ou because  
The dumb dog has to go.  
  
Mother doesn't want a dog.  
Mother says they shed,  
And always let the strangers in  
And bark at friends instead  
  
They do disgraceful things on rugs,  
And track mud on the floor,  
And flop upon your bed at night  
And snore their doggy snore.  
  
Mother doesn't want a dog.  
She's making a mistake.  
Because, more than a dog, I think  
She will not want this snake.  
  